### ISSUE TITLE
Using PHP images in Gitlab CI errors

### ISSUE THREAD

**Issue by Nikschavan** [devilbox/docker-php-fpm#122]
When using the images in the Gitlab CI enviornment the fpm process stays waiting until finally timeout. 

![image](https://user-images.githubusercontent.com/2931091/63089907-238d7f80-bf77-11e9-8365-093567a06736.png)

Here is a the gitlab-ci.yml file that I am trying to use - 

```
variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql

Test:
  image: devilbox/php-fpm:7.3-work
  services:
    - mysql:5.6
  script:
  # Install PHPCS and WPCS
  - composer install

  - vendor/bin/phpcs
  - if find . -name "*.php" ! -path "./vendor/*" ! -path "./admin/bsf-core/*" -exec php -l {} \; | grep "Errors parsing"; then exit 1; fi
  - vendor/bin/phpunit 
```

Just swapping PHP image with other php images works as expected. eg -  `wordpressdevelop/php:7.3-fpm` or `nikschavan/docker-php:7.1`

Any solution to how these images can be used in the Gitlab CI environment?
