### ISSUE TITLE
PHP 7.1 returns Illegal instruction

### ISSUE THREAD

**Issue by kunago** [devilbox/docker-php-fpm#133]
With some recent update of php71 docker image I started receiving "Illegal instruction (core dumped)" when I try to run any php code, even with "php -v" or "php -i". It results in the docker image restarting all the time.

PHP works fine with php71-base but starts to crash with php71-mods and also php71-prod.

**Comment by cytopia** [comment]
Do you have some PHP code on which I can reproduce the behaviour?

**Comment by kunago** [comment]
There is nothing I need to do except for pulling the image and starting it. No code is needed, it is failing to start immediatelly and restarts all the time in loop.

**Comment by cytopia** [comment]
This works fine for me with `docker run -it --rm devilbox/php-fpm:7.1-mods`.
Do you use any other docker run command?

**Comment by kunago** [comment]
I tried to go with your code but nothing really happened and the container did not appear among those already running. As I am using docker-compose instead, this is what I see:
```
root@server:~# docker-compose ps
         Name                       Command                 State                            Ports
-------------------------------------------------------------------------------------------------------------------------
webhosting_php71_1       /docker-entrypoint.sh /usr ...   Restarting

```
and this is the docker-compose.yml part:
```
version: '3'
services:
  php71:
    image: devilbox/php-fpm:7.1-mods
    environment:
      NEW_UID: ${ENV_PHP_NEW_UID}
      NEW_GID: ${ENV_PHP_NEW_GID}
      TIMEZONE: ${ENV_PHP_TIMEZONE}
    volumes:
      - /opt/webhosting/data/caddy:/srv
      - /opt/webhosting/config/php71/php-custom.d:/etc/php-custom.d
      - /opt/webhosting/config/php71/php-fpm-custom.d:/etc/php-fpm-custom.d
    networks:
      - backend
    restart: always
```
Do you see anything suspicious? As I am running also PHP 7.3 and I am using the same settings, I have no idee what is wrong with the php7.1-mods image.

**Comment by cytopia** [comment]
Did you ensure to remove old configuration via:
```
docker-compose rm -f
```

I've used the following configuration to start it up:
```yml
version: '3'
services:
  php71:
    image: devilbox/php-fpm:7.1-mods
    environment:
      NEW_UID: 1000
      NEW_GID: 1000
      TIMEZONE: Europe/Berlin
      DEBUG_ENTRYPOINT: 2
    volumes:
      - ./data:/srv
      - ./php-custom.d:/etc/php-custom.d
      - ./php-fpm-custom.d:/etc/php-fpm-custom.d
    restart: always
```

Note, I've also added `DEBUG_ENTRYPOINT: 2` for a very verbose output which looks like this:


```bash
$ docker-compose up

php71_1  | [INFO] Debug level: 2
php71_1  | [INFO] Changing user 'devilbox' uid to: 1000
php71_1  | root $ usermod -u 1000 devilbox
php71_1  | usermod: no changes
php71_1  | root $ chown -R devilbox /home/devilbox
php71_1  | root $ chown -R devilbox /var/lib/php/session
php71_1  | root $ chown -R devilbox /var/lib/php/wsdlcache
php71_1  | [INFO] Changing group 'devilbox' gid to: 1000
php71_1  | root $ groupmod -g 1000 devilbox
php71_1  | root $ chown -R :devilbox /home/devilbox
php71_1  | root $ chown -R :devilbox /var/lib/php/session
php71_1  | root $ chown -R :devilbox /var/lib/php/wsdlcache
php71_1  | [INFO] Starting PHP 7.1.33 (fpm-fcgi) (built: Oct 25 2019 06:39:47)
php71_1  | [16-Nov-2019 12:18:39] WARNING: Nothing matches the include pattern '/usr/local/etc/php-fpm.d/*.conf' from /usr/local/etc/php-fpm.conf at line 90.
php71_1  | [16-Nov-2019 12:18:39] NOTICE: fpm is running, pid 1
php71_1  | [16-Nov-2019 12:18:39] NOTICE: ready to handle connections
```

All seems to be fine.
Try adding `DEBUG_ENTRYPOINT: 2` and let me know what docker logs is showing.

**Comment by kunago** [comment]
I was sure to remove all unnecessary images, containers and volumes:
```
docker image prune -a
docker volume prune
docker container prune
docker-compose rm -f
```

Then I used this docker-compose.yml file (part of it):
```
version: '3'
services:
  php71:
    image: devilbox/php-fpm:7.1-mods
    environment:
      NEW_UID: ${ENV_PHP_NEW_UID}
      NEW_GID: ${ENV_PHP_NEW_GID}
      TIMEZONE: ${ENV_PHP_TIMEZONE}
      DEBUG_ENTRYPOINT: 2
      DOCKER_LOGS: 0
    volumes:
      - /opt/webhosting/data/caddy:/srv
      - /opt/webhosting/config/php71/php-custom.d:/etc/php-custom.d
      - /opt/webhosting/config/php71/php-fpm-custom.d:/etc/php-fpm-custom.d
    networks:
      - backend
    restart: always
```

It just restarts infinitely:
```
root@server:~/web# docker-compose logs --tail=100 php71
Attaching to webhosting_php71_1
php71_1      | root $ chown -R devilbox /home/devilbox
php71_1      | root $ chown -R devilbox /var/lib/php/session
php71_1      | root $ chown -R devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Changing group 'devilbox' gid to: 33
php71_1      | root $ groupmod -g 33 devilbox
php71_1      | root $ chown -R :devilbox /home/devilbox
php71_1      | root $ chown -R :devilbox /var/lib/php/session
php71_1      | root $ chown -R :devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Starting
php71_1      | [INFO] Debug level: 2
php71_1      | [INFO] Changing user 'devilbox' uid to: 33
php71_1      | root $ usermod -u 33 devilbox
php71_1      | usermod: no changes
php71_1      | root $ chown -R devilbox /home/devilbox
php71_1      | root $ chown -R devilbox /var/lib/php/session
php71_1      | root $ chown -R devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Changing group 'devilbox' gid to: 33
php71_1      | root $ groupmod -g 33 devilbox
php71_1      | root $ chown -R :devilbox /home/devilbox
php71_1      | root $ chown -R :devilbox /var/lib/php/session
php71_1      | root $ chown -R :devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Starting
php71_1      | [INFO] Debug level: 2
php71_1      | [INFO] Changing user 'devilbox' uid to: 33
php71_1      | root $ usermod -u 33 devilbox
php71_1      | usermod: no changes
php71_1      | root $ chown -R devilbox /home/devilbox
php71_1      | root $ chown -R devilbox /var/lib/php/session
php71_1      | root $ chown -R devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Changing group 'devilbox' gid to: 33
php71_1      | root $ groupmod -g 33 devilbox
php71_1      | root $ chown -R :devilbox /home/devilbox
php71_1      | root $ chown -R :devilbox /var/lib/php/session
php71_1      | root $ chown -R :devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Starting
php71_1      | [INFO] Debug level: 2
php71_1      | [INFO] Changing user 'devilbox' uid to: 33
php71_1      | root $ usermod -u 33 devilbox
php71_1      | usermod: no changes
php71_1      | root $ chown -R devilbox /home/devilbox
php71_1      | root $ chown -R devilbox /var/lib/php/session
php71_1      | root $ chown -R devilbox /var/lib/php/wsdlcache
php71_1      | [INFO] Changing group 'devilbox' gid to: 33
php71_1      | root $ groupmod -g 33 devilbox
php71_1      | root $ chown -R :devilbox /home/devilbox
php71_1      | root $ chown -R :devilbox /var/lib/php/session
php71_1      | root $ chown -R :devilbox /var/lib/php/wsdlcache
```

As I was able to trace the error to some point, I found out that in the "base" image php exists, while in the "mods" image it fails to even show the php version when I run "php -v". The return code is "Illegal instruction (core dumped)".
