### ISSUE TITLE
For devs and contributors audience - How to handle an add new PHP modules in Docker images

### ISSUE THREAD

**Issue by llaville** [devilbox/docker-php-fpm#215]
**Goal of this feature request:**

- **avoid common errors** for contributors that would like to help in this project: Docker PHP fpm images
- **explain for new users and beginners** of the Devilbox how we can handle existing PHP modules and add new ones
- **suggest an enhancement of current implementation** to simplify installation of PHP extensions

TLDR;

## Avoid common errors

When new users and beginners of the Devilbox want to contribute first, they changed contents of https://github.com/devilbox/docker-php-fpm/tree/master/Dockerfiles directly by commits and PR (Pull Request)
==> **This is a wrong way !**
You MUST use the `Makefile` that handle all necessary tools to handle the Build Helper available at https://github.com/devilbox/docker-php-fpm/tree/master/build (based on [Ansible](https://www.ansible.com/) technology)

## Explain how to use the Build Helper with Makefile

If you don't remember targets in the `Makefile`, invoke it without arguments (`make`), and you will display the help screen as follow : 

```

             _         _ _ _            __   _           ___
           _| |___ _ _<_| | |_ _____   / ___| |_ ___ ___| | ___._ _ _
          / . / ._| | | | | . / . \ \// | . | . | . |___| || . | ' ' |
          \___\___|__/|_|_|___\___/\_/_/|  _|_|_|  _/   |_||  _|_|_|_|
                                        |_|     |_|        |_|


Targets
--------------------------------------------------------------------------------

lint                          Lint project files and repository

gen-readme [VERSION=]         Update README with PHP modules from built images.
gen-dockerfiles [FAIL_FAST=]  Generate Dockerfiles from templates.

build-base VERSION= [ARGS=]   Build base image by specified version
build-mods VERSION= [ARGS=]   Build mods image by specified version
build-prod VERSION= [ARGS=]   Build prod image by specified version
build-work VERSION= [ARGS=]   Build work image by specified version

rebuild-base VERSION= [ARGS=] Rebuild base image by specified version
rebuild-mods VERSION= [ARGS=] Rebuild mods image by specified version
rebuild-prod VERSION= [ARGS=] Rebuild prod image by specified version
rebuild-work VERSION= [ARGS=] Rebuild work image by specified version

test-base VERSION=            Test base image by specified version
test-mods VERSION=            Test mods image by specified version
test-prod VERSION=            Test prod image by specified version
test-work VERSION=            Test work image by specified version


Variables
--------------------------------------------------------------------------------

VERSION                       One of '5.2', '5.3', '5.4', '5.5', '5.6', '7.0',
                                      '7.1', '7.2', '7.3', '7.4', '8.0', '8.1'.
                              For gen-readme target it is optional and if not
                              specified, it will generate for all versions.

FAIL_FAST                     Either 'True' or 'False' (defaults to 'False').
                              If set to 'True', each module install has an
                              immediate check, which is very slow for CI, but
                              yields errors immediately.
                              If set to 'False', checks are done at the end.

ARGS                          Can be added to all build-* and rebuild-* targets
                              to supply additional docker build options.
```

We will explain in few seconds how to modify properties of a PHP modules, add a new one, or remove an existing.

But now note that before to build or rebuild your Docker images you MUST regenerate the Dockerfiles (remember those ones you didn't modified by hand, see previous chapter).
Invoke the `Makefile` with right target:  `make gen-dockerfiles`

You should got none errors at end of command run, like that: 
```
PLAY RECAP *************************************************************************************************************************************************
php-5.2                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-5.3                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-5.4                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-5.5                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-5.6                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-7.0                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-7.1                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-7.2                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-7.3                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-7.4                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-8.0                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
php-8.1                    : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Then for each PHP version you want to build new copy of Docker images, you have to invoke following commands.
Example for PHP 7.4.x

- make build-base VERSION=7.4`
- make build-mods VERSION=7.4`
- make build-prod VERSION=7.4`
- make build-work VERSION=7.4`

**TIP** Use the rebuild-* targets if you don't want to use Docker cache of previous builds.

* **(re)build-base** is only necessary when a new PHP version is released
* **(re)build-mods** is only necessary when you change a PHP module properties or add/remove one
* **(re)build-prod** is necessary when previous ones were built
* **(re)build-work** is necessary when previous ones were built and especially if you removed or add a new tool 

In current implementation, PHP modules (extensions) definition and enable are defined in `build/ansible/group_vars/all/mods.yml` file

See enable on `extensions_enabled` section : https://github.com/devilbox/docker-php-fpm/blob/0.128/build/ansible/group_vars/all/mods.yml#L14
See definition on `extension_available` section : https://github.com/devilbox/docker-php-fpm/blob/0.128/build/ansible/group_vars/all/mods.yml#L146

These declarations suffer (in my opinion) of two major point:
- we cannot Build your own version of php-fpm:x.y-mods and php-fpm:x.y-work without to modify https://github.com/devilbox/docker-php-fpm/blob/0.128/build/ansible/group_vars/all/mods.yml and chance to commit it by error in a new PR
- PHP extensions enable must follow specific order required by modules itself. This logic should be transparent for all users !

This is the reason why I propose this new feature request to change it and simplify current implementation.

## Enhancement of current implementation

**Solving the first point** Split definition file that should occurs only when we add new PHP extension or modify properties of existing modules, and PHP extension enable.

- Keep only `extensions_available` section in `build/ansible/group_vars/all/mods.yml` file
- Add new YAML files to declare a new definition to use in `build/ansible/roles/template/vars` directory
- Keep fallback to current implementation when none new declaration files are present by `build/ansible/roles/template/vars/main.yml` which is a copy of current `build/ansible/group_vars/all/mods.yml` 

Example by using only PHP core bundled modules and limited tools. File is named `build/ansible/roles/template/vars/core_enabled_cannot_disabled.yml` (naming is free, use whatever you want)

```yaml
---

# -------------------------------------------------------------------------------------------------
# Extensions to enable (in defined order)
# -------------------------------------------------------------------------------------------------
extensions_enabled: []

# -------------------------------------------------------------------------------------------------
# PHP Composer packages to install
# -------------------------------------------------------------------------------------------------
composer_enabled: []

# -------------------------------------------------------------------------------------------------
# Ruby gem packages to install
# -------------------------------------------------------------------------------------------------
gem_enabled: []

# -------------------------------------------------------------------------------------------------
# Node npm packages to install
# -------------------------------------------------------------------------------------------------
npm_enabled: []

# -------------------------------------------------------------------------------------------------
# Python pip packages to install
# -------------------------------------------------------------------------------------------------
pip_enabled: []

# -------------------------------------------------------------------------------------------------
# Software to install (in defined order)
# -------------------------------------------------------------------------------------------------
software_enabled:
  # Composer, pip and nvm need to be first, others rely on it
  - composer
  - pip
  - nvm
  # Normal packages start here
  # Cleanup needs to be last
  - cleanup
```

Another example with limited PHP extensions and tools named `build/ansible/roles/template/vars/php_compatinfo_db.yml`, I used to build Docker images for my project https://github.com/llaville/php-compatinfo-db
```yaml
---

# -------------------------------------------------------------------------------------------------
# Extensions to enable (in defined order)
# -------------------------------------------------------------------------------------------------
extensions_enabled:
  - amqp
  - apcu
  - ast
  - bcmath
  - bz2
  - calendar
  - enchant
  - exif
  - ffi
  - gd
  - gettext
  - gmp
  - http
  - igbinary
  - imagick
  - imap
  - intl
  - ldap
  - lzf
  - mailparse
  - mcrypt
  - memcache
  - memcached
  - mongodb
  - msgpack
  - mysqli
  - oauth
  - oci8
  - odbc
  - opcache
  - pcntl
  - pdo_mysql
  - pdo_oci
  - pdo_pgsql
  - pdo_sqlsrv
  - pgsql
  - propro
  - raphf
  - rdkafka
  - recode
  - redis
  - snmp
  - soap
  - solr
  - sqlsrv
  - ssh2
  - sysvmsg
  - sysvsem
  - sysvshm
  - tidy
  - uopz
  - wddx
  - xdebug
  - xhprof
  - xmldiff
  - xmlrpc
  - xsl
  - yaml
  - zip
  - zstd

# -------------------------------------------------------------------------------------------------
# PHP Composer packages to install
# -------------------------------------------------------------------------------------------------
composer_enabled: []

# -------------------------------------------------------------------------------------------------
# Ruby gem packages to install
# -------------------------------------------------------------------------------------------------
gem_enabled: []

# -------------------------------------------------------------------------------------------------
# Node npm packages to install
# -------------------------------------------------------------------------------------------------
npm_enabled: []

# -------------------------------------------------------------------------------------------------
# Python pip packages to install
# -------------------------------------------------------------------------------------------------
pip_enabled: []

# -------------------------------------------------------------------------------------------------
# Software to install (in defined order)
# -------------------------------------------------------------------------------------------------
software_enabled:
  # Composer, pip and nvm need to be first, others rely on it
  - composer
  - pip
  - nvm
  # Normal packages start here
  # Cleanup needs to be last
  - cleanup
```

Regenerate Dockerfiles by invoking following command: `make gen-dockerfiles ARGS="--extra-vars=@roles/template/vars/core_enabled_cannot_disabled.yml"`
Or `make gen-dockerfiles ARGS="--extra-vars=@roles/template/vars/php_compatinfo_db.yml"`

Then follow standard Docker images build processes as explained in previous chapter.

**Solving the second point** Change current PHP extensions installation in `build/ansible/DOCKERFILES/Dockerfile-mods.j2` Jinja2 template file by using the open source project https://github.com/mlocati/docker-php-extension-installer
Advanges: it handle correctly PHP modules dependency order (so using a `extensions_enabled` is alphabetic order is a big plus) and librairies required at build and run time.

Last but not least, keep Backward Compatibility with current implementation by keeping all properties of `extensions_available` section in `build/ansible/group_vars/all/mods.yml` file, especially `disabled`, `<php_version>.version` what are only necessary with new implementation.

And don't forget to change your `docker-compose.override.yml` by using the local docker images built 
```yaml
---
version: '2.3'

# The following override shows an example for the cockroachdb
services:
  php:
    #image: devilbox/php-fpm:${PHP_SERVER}-work-0.127
    image: devilbox/php-fpm:${PHP_SERVER}-work
```

Congratulations for all of you that reached this point. Hope its enough clear, and If not I'm ready to clarify any point that is supposed to be !

A PR will follow to propose new implementation. Especially to @cytopia, I'd like to heard what you think about it 

This report superceeded previous one that could be closed :
* [Build your own version of php-fpm:x.y-mods and php-fpm:x.y-work](https://github.com/devilbox/docker-php-fpm/issues/199)
