### ISSUE TITLE
Set NEW_UID and NEW_GID inside custom Dockerfile

### ISSUE THREAD

**Issue by valentinocossar** [devilbox/docker-php-fpm#228]
Hi,

I'm trying to use `devilbox/php-fpm:8.0-prod` as FROM to build a new image. I would like to pass NEW_UID and NEW_GID to the base image to set permissions properly. How can I achieve this? Could you help me please?

I have this `docker-compose.yml` file:

```yml
version: "3"

services:
  php-fpm:
    build:
      context: ./development/php-fpm
      dockerfile: Dockerfile
      args:
        NEW_UID: 501
        NEW_GID: 20
        COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
        COMPOSER_VERSION: "2.2.4"
        WP_CLI_VERSION: "2.4.0"
        NODE_MAJOR_VERSION: "14"
    container_name: "${COMPOSE_PROJECT_NAME}-php-fpm"
    volumes:
      - ./web:/var/www/html/web
    depends_on:
      - mysql
      - mailhog

  nginx:
    image: nginx:latest
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    volumes:
      - ./development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./development/nginx/templates:/etc/nginx/templates
      - ./development/certs:/etc/nginx/certs
      - ./web:/var/www/html/web
    ports:
      - "443:443"
      - "80:80"
    environment:
      NGINX_HOST: "${COMPOSE_PROJECT_NAME}.pot.test"
    depends_on:
      - php-fpm

  mysql:
    image: mysql:8.0
    container_name: "${COMPOSE_PROJECT_NAME}-mysql"
    ports:
      - "3306:3306"
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "wordpressmysql:/var/lib/mysql"
    command: --default-authentication-plugin=mysql_native_password

  mailhog:
    image: mailhog/mailhog:latest
    container_name: "${COMPOSE_PROJECT_NAME}-mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  wordpressmysql:
    driver: local
```

And this is the Dockerfile:
```
ARG NEW_UID=$NEW_UID
ARG NEW_GID=$NEW_GID

FROM devilbox/php-fpm:8.0-prod

ARG COMPOSE_PROJECT_NAME=$COMPOSE_PROJECT_NAME
ARG COMPOSER_VERSION=$COMPOSER_VERSION
ARG WP_CLI_VERSION=$WP_CLI_VERSION
ARG NODE_MAJOR_VERSION=$NODE_MAJOR_VERSION

# Install Composer
RUN apt-get -y update && \
  apt-get -y --no-install-recommends install --fix-missing curl && \
  curl -sSL "https://getcomposer.org/installer" | php -- --install-dir=/usr/local/bin --filename=composer --version=$COMPOSER_VERSION

# Install WP-CLI
RUN apt-get -y update && \
  apt-get -y --no-install-recommends install --fix-missing curl && \
  curl -o /usr/local/bin/wp -sSL "https://github.com/wp-cli/wp-cli/releases/download/v$WP_CLI_VERSION/wp-cli-$WP_CLI_VERSION.phar" && \
  chmod +x /usr/local/bin/wp

# Install Node.js 14
RUN apt-get -y update && \
  apt-get -y --no-install-recommends install --fix-missing curl && \
  curl -sSL "https://deb.nodesource.com/setup_$NODE_MAJOR_VERSION.x "| bash - && \
  apt-get install -y nodejs

# Cleaning packages
RUN apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
  rm -rf /var/lib/apt/lists/*

# Cleanup
RUN rm -rf /usr/src/*
```
